### ISSUE TITLE
Compile errors on Clang and GCC

### ISSUE THREAD

**Issue by edubart** [mackron/c89thread#1]
I am unable to use the library with Clang or GCC on Linux, these are the errors:

With clang:
```
./c89thread.h:1411:9: error: use of undeclared identifier 'pSem'; did you mean 'sem'?
    if (pSem->value < pSem->valueMax) {
        ^~~~
        sem
./c89thread.h:1398:27: note: 'sem' declared here
int c89sem_post(c89sem_t* sem)
                          ^
./c89thread.h:1411:23: error: use of undeclared identifier 'pSem'; did you mean 'sem'?
    if (pSem->value < pSem->valueMax) {
                      ^~~~
                      sem
./c89thread.h:1398:27: note: 'sem' declared here
int c89sem_post(c89sem_t* sem)
                          ^
./c89thread.h:1412:9: error: use of undeclared identifier 'pSem'
        pSem->value += 1;
        ^
./c89thread.h:1413:30: error: use of undeclared identifier 'pSem'; did you mean 'sem'?
        pthread_cond_signal(&pSem->cond);
                             ^~~~
                             sem
./c89thread.h:1398:27: note: 'sem' declared here
int c89sem_post(c89sem_t* sem)
                          ^
./c89thread.h:1566:5: error: void function 'c89timespec_get' should not return a value [-Wreturn-type]
    return timespec_get(ts, base);
    ^      ~~~~~~~~~~~~~~~~~~~~~~
```

With GCC:
```
c89thread.h: In function ‘c89sem_post’:
c89thread.h:1411:9: error: ‘pSem’ undeclared (first use in this function)
 1411 |     if (pSem->value < pSem->valueMax) {
      |         ^~~~
c89thread.h:1411:9: note: each undeclared identifier is reported only once for each function it appears in
c89thread.h: In function ‘c89timespec_get’:
c89thread.h:1566:12: warning: ‘return’ with a value, in function returning void [-Wreturn-type]
 1566 |     return timespec_get(ts, base);
      |            ^~~~~~~~~~~~~~~~~~~~~~
c89thread.h:1564:6: note: declared here
 1564 | void c89timespec_get(struct timespec* ts, int base)
      |      ^~~~~~~~~~~~~~~
```

Also when I compile with `-std=c99` or `-std=c89` more error and warnings appears, so the library does not really work with C89 on Linux.

**Comment by edubart** [comment]
I've fixed those errors on my side, the following are errors when compiling with strict standard.

When compile with `-std=gnu89` I get this warning:
```c
c89thread.h: In function ‘c89timespec_get’:
c89thread.h:1566:5: warning: implicit declaration of function ‘timespec_get’; did you mean ‘c89timespec_get’? [-Wimplicit-function-declaration]
 1566 |     timespec_get(ts, base);
      |     ^~~~~~~~~~~~
      |     c89timespec_get
```

When compiling with `-std=c89` I get these errors:
```c
In file included from mt-example.c:4:
c89thread.h: In function ‘c89thrd_sleep’:
c89thread.h:1049:18: warning: implicit declaration of function ‘nanosleep’ [-Wimplicit-function-declaration]
 1049 |     int result = nanosleep(duration, remaining);
      |                  ^~~~~~~~~
c89thread.h: In function ‘c89mtx_init’:
c89thread.h:1114:9: warning: implicit declaration of function ‘pthread_mutexattr_settype’; did you mean ‘pthread_mutexattr_destroy’? [-Wimplicit-function-declaration]
 1114 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         pthread_mutexattr_destroy
c89thread.h:1114:42: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function); did you mean ‘PTHREAD_MUTEX_RECURSIVE_NP’?
 1114 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~
      |                                          PTHREAD_MUTEX_RECURSIVE_NP
c89thread.h:1114:42: note: each undeclared identifier is reported only once for each function it appears in
c89thread.h:1116:42: error: ‘PTHREAD_MUTEX_NORMAL’ undeclared (first use in this function); did you mean ‘PTHREAD_MUTEX_TIMED_NP’?
 1116 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_NORMAL);     /* Will deadlock. Consistent with Win32. */
      |                                          ^~~~~~~~~~~~~~~~~~~~
      |                                          PTHREAD_MUTEX_TIMED_NP
c89thread.h: In function ‘c89mtx_timedlock’:
c89thread.h:1162:14: warning: implicit declaration of function ‘pthread_mutex_timedlock’; did you mean ‘pthread_mutex_trylock’? [-Wimplicit-function-declaration]
 1162 |     result = pthread_mutex_timedlock(mutex, time_point);
      |              ^~~~~~~~~~~~~~~~~~~~~~~
      |              pthread_mutex_trylock
c89thread.h: In function ‘c89timespec_get’:
c89thread.h:1566:5: warning: implicit declaration of function ‘timespec_get’; did you mean ‘c89timespec_get’? [-Wimplicit-function-declaration]
 1566 |     timespec_get(ts, base);
      |     ^~~~~~~~~~~~
      |     c89timespec_get
```

**Comment by mackron** [comment]
Thanks for this. I fixed up those `pSem` errors (a copy/paste error from another code base of mine). Not actually compiled that yet. Will look at those other errors when I can.

The `nanosleep()` one should be fixable. I think I've got something in miniaudio that might be able to clean that up (I hope). The `pthread_mutexattr_settype()` is concerning... Not sure what I'm going to do about that one off the top of my head. The `timespec_get()` error should be fixable with `c89timespec_get()`.

**Comment by edubart** [comment]
By looking in `pthread.h` and `features.h` I noticed that pthread errors go away by doing this:
```C
#define _XOPEN_SOURCE 700L
```
There is written:
```c
   _XOPEN_SOURCE	Includes POSIX and XPG things.  Set to 500 if
			Single Unix conformance is wanted, to 600 for the
			sixth revision, to 700 for the seventh revision.
```

Looks like _XOPEN_SOURCE with 700 is available since a 2008 spec.
Using _XOPEN_SOURCE with 500 I only get the error about the `pthread_mutex_timedlock`. 

The errors also goes away by defining `_GNU_SOURCE` (but I think this would be the same as doing `-std=gnu11`).

**Comment by mackron** [comment]
I was hoping to avoid having to define those. It would good if it could "Just Work" without them. Alas, I don't think that's the practical solution right now, so I've just gone ahead and added this to the top of the file, just above pthread.h:

```c
#ifndef _XOPEN_SOURCE
#define _XOPEN_SOURCE   700
#endif
```

I don't think this is the ideal solution, but for now I think it's the most practical.

I've added native fallbacks for `c89timespec_get()` and `c89thrd_sleep()`, however, so they'll just work without the `_XOPEN_SOURCE` thing.

**Comment by edubart** [comment]
I just tested, now it can compile without C11, good!
It compiles fine with `-std=gnu99` but still fails with `-std=c99`, these are the errors:
```c
thirdparty/c89thread.h: In function ‘c89mtx_init’:
thirdparty/c89thread.h:1212:9: warning: implicit declaration of function ‘pthread_mutexattr_settype’; did you mean ‘pthread_mutexattr_destroy’? [-Wimplicit-function-declaration]
 1212 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |         pthread_mutexattr_destroy
thirdparty/c89thread.h:1212:42: error: ‘PTHREAD_MUTEX_RECURSIVE’ undeclared (first use in this function); did you mean ‘PTHREAD_MUTEX_RECURSIVE_NP’?
 1212 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~
      |                                          PTHREAD_MUTEX_RECURSIVE_NP
thirdparty/c89thread.h:1212:42: note: each undeclared identifier is reported only once for each function it appears in
thirdparty/c89thread.h:1214:42: error: ‘PTHREAD_MUTEX_NORMAL’ undeclared (first use in this function); did you mean ‘PTHREAD_MUTEX_TIMED_NP’?
 1214 |         pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_NORMAL);     /* Will deadlock. Consistent with Win32. */
      |                                          ^~~~~~~~~~~~~~~~~~~~
      |                                          PTHREAD_MUTEX_TIMED_NP
thirdparty/c89thread.h: In function ‘c89mtx_timedlock’:
thirdparty/c89thread.h:1260:14: warning: implicit declaration of function ‘pthread_mutex_timedlock’; did you mean ‘pthread_mutex_trylock’? [-Wimplicit-function-declaration]
 1260 |     result = pthread_mutex_timedlock(mutex, time_point);
      |              ^~~~~~~~~~~~~~~~~~~~~~~
      |              pthread_mutex_trylock
```

**Comment by mackron** [comment]
Those most recent errors will be due to something defining `_XOPEN_SOURCE` before the c89thread implementation.
